service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:349558942960:certificate/dd8f9e63-0d2c-4089-90f3-c49ecd77dbd7"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"

ports:
  web:
    port: 80
    exposedPort: 80

  websecure:
    port: 8000
    exposedPort: 443
    http:
      tls:
        enabled: false

logs:
  general:
    level: DEBUG

additionalArguments:
  - "--accesslog=true"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  # Trust NLB forwarded headers
  - "--entrypoints.web.forwardedHeaders.insecure=true"
  - "--entrypoints.websecure.forwardedHeaders.insecure=true"

  # HTTP -> HTTPS redirect
  - "--entrypoints.web.http.redirections.entrypoint.to=:443"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"


